### ISSUE TITLE
Download generator

### ISSUE THREAD

**Issue by martyn** [255BITS/hypr#10]
Problem:

We want to release newly trained models without releasing the whole app.

Proposed solution:

A `download` button that downloads a model from a specified model url(from the generator 'model_url').  On exception alert the user.

**Comment by TedHoryczun** [comment]
JSON file that has models that can be downloaded. A navigation drawer that can be dynamically changed by this JSON. Having a download button near the model name. Models that can't be accessed by the user are grayed out.
