### ISSUE TITLE
Spike: Inline editing

### ISSUE THREAD

**Issue by martyn** [255BITS/hypr#44]
Description

As a user I want to see my face modifications live in my photo without zooming in or destroying the rest of the photo.

Proposed solution:

Allow for a model with `InlineViewer`.  Instead of rendering to the screen, render to the image replacing the content.  So for example, if the original face is offset by 100,100 and of size 40,40, we will need to run the generator, scale the output of the generator, and place it back into the 100,100 location at 40,40 size(rescaling and translating).

**Comment by mikkel** [comment]
Current bugs:

* [ ] preserve aspect ratio on input image
* [ ] place image back in scene
* [ ] joinImageWithFace doesn't account for landscape manipulation
